# Файл docker-compose должен начинаться с тега версии.
version: '3'
# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.

services:
  fcgi:
    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.
    # Здесь '/' соответствует пути к папке сервера,
    # которая содержит соответствующий Dockerfile.
    build: /home/howlansh/DO5_SimpleDocker-1/src
    image: fcgi:test
    networks:
      - plastic

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"  # Маппинг портов 8080 контейнера на 80 порт локальной машины
    networks:
      - plastic
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fcgi

networks:
  plastic:
    driver: bridge